language: java
jdk:
  - oraclejdk8
before_install:  
   - "echo skipped"  
install:  
  - "echo skipped" 
#install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
  - mvn test
notifications:  
  email:  
    recipients:  
      - 195446040@qq.com
    on_success: always 
    on_failure: always