language: java
jdk:
  - oraclejdk8
before_install:  
   - "echo skipped"  
install:  
  - "echo skipped" 
#install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true
  - mvn test